const { queryOne, queryAll, runSql } = require('../config/db');
const bcrypt = require('bcryptjs');

// Admin password from env or default
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '1993L1nh$';

const lessons = [
  { title: 'Common Verb + Noun (make/do/take)', titleVi: 'Động từ + Danh từ cơ bản', desc: 'Essential verb-noun collocations with make, do, take, have', descVi: 'Các cụm động từ + danh từ thông dụng', level: 'B1', order: 1, src: 'Cambridge Intermediate', locked: 0 },
  { title: 'Adjective + Noun Basics', titleVi: 'Tính từ + Danh từ cơ bản', desc: 'Common adjective-noun pairings', descVi: 'Các cụm tính từ + danh từ phổ biến', level: 'B1', order: 2, src: 'Cambridge Intermediate', locked: 0 },
  { title: 'Verb + Preposition Essentials', titleVi: 'Động từ + Giới từ thiết yếu', desc: 'Key verb-preposition combinations', descVi: 'Các cụm động từ + giới từ quan trọng', level: 'B1', order: 3, src: 'Oxford Collocations Dict', locked: 0 },
  { title: 'Adverb + Adjective', titleVi: 'Trạng từ + Tính từ', desc: 'Intensifying adverbs with adjectives', descVi: 'Trạng từ tăng cường + tính từ', level: 'B2', order: 4, src: 'Cambridge Intermediate', locked: 1 },
  { title: 'Education & Academic Life', titleVi: 'Giáo dục & Học thuật', desc: 'Collocations for academic contexts', descVi: 'Cụm từ trong ngữ cảnh học thuật', level: 'B2', order: 5, src: 'Cambridge Advanced Unit 8', locked: 1 },
  { title: 'Business & Work', titleVi: 'Kinh doanh & Công việc', desc: 'Professional collocations', descVi: 'Cụm từ chuyên nghiệp', level: 'B2', order: 6, src: 'Cambridge Advanced Units 5-7', locked: 1 },
  { title: 'Feelings & Relationships', titleVi: 'Cảm xúc & Mối quan hệ', desc: 'Expressing emotions', descVi: 'Diễn đạt cảm xúc', level: 'B2', order: 7, src: 'Cambridge Advanced Unit 41', locked: 1 },
  { title: 'News & Current Affairs', titleVi: 'Tin tức & Thời sự', desc: 'Media collocations', descVi: 'Cụm từ báo chí', level: 'B2-C1', order: 8, src: 'Cambridge Advanced Units 22-23', locked: 1 },
  { title: 'Environment & Society', titleVi: 'Môi trường & Xã hội', desc: 'Environmental collocations', descVi: 'Cụm từ về môi trường', level: 'C1', order: 9, src: 'Cambridge Advanced', locked: 1 },
  { title: 'Advanced Verb + Noun', titleVi: 'Động từ + Danh từ nâng cao', desc: 'Sophisticated verb-noun collocations', descVi: 'Cụm động từ nâng cao', level: 'C1', order: 10, src: 'Oxford Collocations Dict', locked: 1 },
  { title: 'Formal & Academic Register', titleVi: 'Ngôn ngữ trang trọng', desc: 'Formal register collocations', descVi: 'Cụm từ trang trọng', level: 'C1', order: 11, src: 'Cambridge Advanced Units 3-4', locked: 1 },
  { title: 'Idiomatic Collocations', titleVi: 'Cụm từ thành ngữ', desc: 'Semi-fixed idiomatic expressions', descVi: 'Thành ngữ cố định', level: 'C1', order: 12, src: 'Cambridge Advanced', locked: 1 },
  { title: 'Advanced Exam Collocations', titleVi: 'Collocation thi nâng cao', desc: 'From CAE/CPE past papers', descVi: 'Từ đề thi CAE/CPE', level: 'C1+', order: 13, src: 'CAE/CPE', locked: 1 },
  { title: 'CNN-Style Challenge', titleVi: 'Bộ thử thách CNN', desc: 'CNN exam difficulty', descVi: 'Theo chuẩn đề CNN', level: 'C1+', order: 14, src: 'CNN patterns', locked: 1 },
];

const cols = {
  1:[['make a decision','đưa ra quyết định','You need to make a decision before the deadline.','verb+noun',1],['make progress','tiến bộ','She has made significant progress in her studies.','verb+noun',1],['make an effort','nỗ lực','Please make an effort to arrive on time.','verb+noun',1],['make a mistake','mắc lỗi','Everyone makes mistakes when learning.','verb+noun',1],['make a contribution','đóng góp','He made a valuable contribution to the project.','verb+noun',2],['make a living','kiếm sống','He makes a living by teaching English.','verb+noun',2],['make an impression','tạo ấn tượng','She made a good impression at the interview.','verb+noun',2],['do research','nghiên cứu','Scientists do research to find new treatments.','verb+noun',1],['do harm','gây hại','Pollution does great harm to the environment.','verb+noun',2],['do business','kinh doanh','They do business with companies worldwide.','verb+noun',1],['do damage','gây thiệt hại','The storm did serious damage to the buildings.','verb+noun',2],['take action','hành động','The government must take action to reduce pollution.','verb+noun',1],['take responsibility','chịu trách nhiệm','You should take responsibility for your actions.','verb+noun',1],['take advantage of','tận dụng','Take advantage of every learning opportunity.','verb+noun',2],['take into account','xem xét, cân nhắc','We must take all factors into account.','verb+noun',2],['take place','diễn ra','The exam will take place next Monday.','verb+noun',1],['have access to','có quyền truy cập','Students have access to the online library.','verb+noun',2],['have an impact on','có tác động đến','Technology has a huge impact on education.','verb+noun',2],['give advice','đưa ra lời khuyên','My teacher gave me useful advice.','verb+noun',1],['give priority to','ưu tiên','We should give priority to safety.','verb+noun',2]],
  2:[['heavy rain','mưa lớn','Heavy rain caused flooding in the area.','adj+noun',1],['strong opinion','ý kiến mạnh mẽ','She has a strong opinion on this matter.','adj+noun',1],['close friend','bạn thân','He is one of my closest friends.','adj+noun',1],['bright future','tương lai tươi sáng','She has a bright future ahead of her.','adj+noun',1],['deep concern','lo ngại sâu sắc','There is deep concern about climate change.','adj+noun',2],['keen interest','quan tâm mạnh mẽ','He has a keen interest in science.','adj+noun',2],['serious consequences','hậu quả nghiêm trọng','Cheating can have serious consequences.','adj+noun',2],['significant impact','tác động đáng kể','The policy had a significant impact.','adj+noun',2],['wide range','phạm vi rộng','The shop offers a wide range of products.','adj+noun',1],['sharp increase','tăng mạnh','There has been a sharp increase in prices.','adj+noun',2],['harsh criticism','chỉ trích gay gắt','The plan faced harsh criticism.','adj+noun',2],['vast majority','đại đa số','The vast majority of students passed.','adj+noun',2],['fatal mistake','sai lầm chết người','One fatal mistake can ruin everything.','adj+noun',2],['crucial role','vai trò quan trọng','Teachers play a crucial role in society.','adj+noun',2],['fierce competition','cạnh tranh khốc liệt','There is fierce competition among candidates.','adj+noun',2],['narrow escape','thoát trong gang tấc','He had a narrow escape from the accident.','adj+noun',3],['grave danger','nguy hiểm nghiêm trọng','The species is in grave danger.','adj+noun',3],['broad knowledge','kiến thức rộng','A teacher needs broad knowledge.','adj+noun',2],['steady growth','tăng trưởng ổn định','The economy showed steady growth.','adj+noun',2],['bitter cold','lạnh cắt da','We endured the bitter cold of winter.','adj+noun',2]],
  3:[['depend on','phụ thuộc vào','Success depends on hard work.','verb+prep',1],['apply for','nộp đơn xin','She applied for a scholarship.','verb+prep',1],['consist of','bao gồm','The team consists of 10 members.','verb+prep',1],['result in','dẫn đến','Poor planning resulted in failure.','verb+prep',2],['account for','chiếm, giải thích','Tourism accounts for 20% of income.','verb+prep',2],['cope with','đối phó với','She learned to cope with stress.','verb+prep',2],['contribute to','đóng góp vào','Exercise contributes to good health.','verb+prep',1],['refer to','đề cập đến','The author refers to several studies.','verb+prep',1],['suffer from','chịu đựng','Many people suffer from allergies.','verb+prep',1],['lead to','dẫn đến','Lack of sleep can lead to health problems.','verb+prep',1],['benefit from','hưởng lợi từ','Students benefit from extra practice.','verb+prep',1],['succeed in','thành công trong','She succeeded in passing the exam.','verb+prep',1],['insist on','khăng khăng','He insisted on paying for the meal.','verb+prep',2],['concentrate on','tập trung vào','Please concentrate on your work.','verb+prep',1],['comply with','tuân thủ','All staff must comply with the rules.','verb+prep',3],['derive from','bắt nguồn từ','This word derives from Latin.','verb+prep',3],['invest in','đầu tư vào','The government invested in education.','verb+prep',2],['object to','phản đối','Residents objected to the plan.','verb+prep',2],['approve of','tán thành','Her parents did not approve of it.','verb+prep',2],['interfere with','can thiệp vào','Noise interferes with concentration.','verb+prep',2]],
  4:[['deeply concerned','lo ngại sâu sắc','Parents are deeply concerned about safety.','adv+adj',2],['highly unlikely','rất khó xảy ra','It is highly unlikely they will agree.','adv+adj',2],['perfectly acceptable','hoàn toàn chấp nhận','This is perfectly acceptable.','adv+adj',2],['wildly inaccurate','hoàn toàn sai lệch','The report was wildly inaccurate.','adv+adj',3],['bitterly disappointed','thất vọng cay đắng','He was bitterly disappointed.','adv+adj',3],['fully aware','hoàn toàn nhận thức','She was fully aware of the risk.','adv+adj',2],['strongly recommend','đặc biệt khuyến nghị','I strongly recommend this book.','adv+adj',2],['closely related','liên quan chặt chẽ','These issues are closely related.','adv+adj',2],['widely recognized','công nhận rộng rãi','She is widely recognized as an expert.','adv+adj',2],['heavily influenced','bị ảnh hưởng nặng','His work was heavily influenced by art.','adv+adj',2],['readily available','sẵn có','Information is readily available online.','adv+adj',2],['strictly prohibited','nghiêm cấm','Smoking is strictly prohibited here.','adv+adj',2],['blissfully unaware','không hề hay biết','She was blissfully unaware of danger.','adv+adj',3],['abundantly clear','rõ ràng tuyệt đối','He made it abundantly clear.','adv+adj',3],['critically important','cực kỳ quan trọng','Education is critically important.','adv+adj',2],['severely damaged','hư hại nghiêm trọng','The building was severely damaged.','adv+adj',2],['utterly ridiculous','hoàn toàn vô lý','The suggestion was utterly ridiculous.','adv+adj',3],['painfully obvious','rõ ràng đến đau đớn','It was painfully obvious he was lying.','adv+adj',3],['genuinely interested','thực sự quan tâm','He seemed genuinely interested.','adv+adj',2],['largely responsible','chịu trách nhiệm chính','He was largely responsible for success.','adv+adj',2]],
  5:[['attend a lecture','tham dự bài giảng','Students must attend all lectures.','verb+noun',1],['gain knowledge','thu kiến thức','Reading helps you gain knowledge.','verb+noun',1],['submit an assignment','nộp bài tập','Please submit your assignment by Friday.','verb+noun',1],['pursue a career','theo đuổi sự nghiệp','She plans to pursue a career in medicine.','verb+noun',2],['broaden horizons','mở rộng tầm nhìn','Traveling broadens your horizons.','verb+noun',2],['draw a conclusion','rút ra kết luận','We can draw a conclusion from the data.','verb+noun',2],['conduct an experiment','tiến hành thí nghiệm','Scientists conducted an experiment.','verb+noun',2],['acquire skills','tiếp thu kỹ năng','Students acquire skills through practice.','verb+noun',2],['meet a deadline','hoàn thành đúng hạn','She always meets her deadlines.','verb+noun',2],['revise notes','ôn lại ghi chú','I need to revise my notes before the exam.','verb+noun',1],['critical analysis','phân tích phản biện','The essay requires critical analysis.','adj+noun',3],['steep learning curve','đường học tập dốc','The software has a steep learning curve.','adj+noun',3],['thirst for knowledge','khao khát kiến thức','Children have a thirst for knowledge.','noun+prep',3],['gifted child','trẻ có năng khiếu','Programs for gifted children need funding.','adj+noun',2],['hands-on experience','kinh nghiệm thực tế','Internships provide hands-on experience.','adj+noun',2],['working hypothesis','giả thuyết làm việc','Let us start with a working hypothesis.','adj+noun',3],['confront an issue','đối mặt vấn đề','We must confront this issue head-on.','verb+noun',3],['enroll in a course','ghi danh khóa học','She enrolled in an online course.','verb+prep',2],['pass with flying colors','đỗ xuất sắc','He passed with flying colors.','verb+prep',2],['mature student','sinh viên trưởng thành','Many mature students return to university.','adj+noun',2]],
  6:[['make a living','kiếm sống','He makes a living by teaching.','verb+noun',2],['take up a post','nhận chức vụ','She took up a post at the university.','verb+noun',3],['land a job','kiếm được việc','He landed a job at a top company.','verb+noun',2],['move up the ladder','thăng tiến','She quickly moved up the ladder.','verb+noun',3],['meet a target','đạt mục tiêu','The team met all their targets.','verb+noun',2],['run a business','điều hành doanh nghiệp','She runs a successful business.','verb+noun',2],['heavy workload','khối lượng công việc nặng','Teachers often face a heavy workload.','adj+noun',2],['job description','mô tả công việc','Read the job description carefully.','noun+noun',2],['menial tasks','công việc tầm thường','Nobody wants to do menial tasks.','adj+noun',3],['earn a reputation','tạo dựng danh tiếng','She earned a reputation for excellence.','verb+noun',3],['fierce competition','cạnh tranh khốc liệt','There is fierce competition for jobs.','adj+noun',2],['stimulate growth','kích thích tăng trưởng','Tax cuts can stimulate growth.','verb+noun',3],['hike in prices','giá tăng mạnh','There was a sharp hike in prices.','noun+prep',3],['market share','thị phần','The company gained market share.','noun+noun',2],['consumer demands','nhu cầu người tiêu dùng','Consumer demands are changing.','noun+noun',2],['work overtime','làm thêm giờ','I had to work overtime this week.','verb+noun',1],['attend a meeting','tham dự cuộc họp','All staff must attend the meeting.','verb+noun',1],['give a presentation','thuyết trình','She gave an excellent presentation.','verb+noun',2],['get promoted','được thăng chức','He got promoted after two years.','verb+noun',2],['lose ones livelihood','mất kế sinh nhai','Many farmers lost their livelihood.','verb+noun',3]],
  7:[['burst into tears','bật khóc','She burst into tears when she heard.','verb+prep',2],['lose ones temper','mất bình tĩnh','Try not to lose your temper.','verb+noun',2],['close relationship','mối quan hệ thân thiết','They have a very close relationship.','adj+noun',1],['mutual respect','tôn trọng lẫn nhau','A good friendship is built on mutual respect.','adj+noun',2],['deeply moved','xúc động sâu sắc','I was deeply moved by her story.','adv+adj',2],['feel devastated','cảm thấy suy sụp','He felt devastated after the loss.','verb+adj',3],['overwhelming joy','niềm vui tràn ngập','She felt overwhelming joy.','adj+noun',2],['bitter resentment','sự oán giận cay đắng','He harbored bitter resentment.','adj+noun',3],['forge a friendship','xây dựng tình bạn','They forged a lifelong friendship.','verb+noun',3],['nurture a relationship','vun đắp mối quan hệ','Good relationships need to be nurtured.','verb+noun',3],['profound sadness','nỗi buồn sâu sắc','A feeling of profound sadness.','adj+noun',3],['unconditional love','tình yêu vô điều kiện','Parents show unconditional love.','adj+noun',2],['break someones heart','làm tan nát trái tim','The news broke her heart.','verb+noun',2],['hold a grudge','giữ mối hận thù','He never holds a grudge.','verb+noun',2],['form a bond','hình thành mối liên kết','They formed a strong bond.','verb+noun',2],['grow apart','xa cách dần','As they got older, they grew apart.','verb+adv',2],['feel anxious','cảm thấy lo lắng','She felt anxious about the exam.','verb+adj',1],['emotional support','hỗ trợ tinh thần','Friends provide emotional support.','adj+noun',2],['strong attachment','sự gắn bó mạnh mẽ','Children form strong attachments.','adj+noun',2],['express gratitude','bày tỏ lòng biết ơn','I want to express my gratitude.','verb+noun',2]],
  8:[['declare independence','tuyên bố độc lập','The country declared independence.','verb+noun',3],['reach an agreement','đạt thỏa thuận','The two sides reached an agreement.','verb+noun',2],['bow to pressure','nhượng bộ áp lực','The government bowed to pressure.','verb+prep',3],['refuse point-blank','từ chối thẳng thừng','She refused point-blank to help.','verb+adv',3],['decline to comment','từ chối bình luận','The minister declined to comment.','verb+prep',3],['gauge reaction','đánh giá phản ứng','They tried to gauge public reaction.','verb+noun',3],['mounting pressure','áp lực gia tăng','There is mounting pressure to act.','adj+noun',3],['heated debate','cuộc tranh luận nóng','The issue sparked a heated debate.','adj+noun',2],['breaking news','tin nóng','We have some breaking news.','adj+noun',1],['public outcry','sự phẫn nộ công chúng','The decision caused a public outcry.','adj+noun',3],['hold talks','tổ chức đàm phán','The leaders agreed to hold talks.','verb+noun',2],['impose sanctions','áp đặt trừng phạt','The UN imposed sanctions.','verb+noun',3],['spark controversy','gây tranh cãi','The policy sparked controversy.','verb+noun',3],['launch an investigation','mở cuộc điều tra','Police launched an investigation.','verb+noun',2],['cast doubt on','đặt nghi vấn về','New evidence cast doubt on the theory.','verb+prep',3],['widespread concern','lo ngại rộng rãi','There is widespread concern about pollution.','adj+noun',2],['take a stance','đưa ra lập trường','The president took a firm stance.','verb+noun',3],['fuel speculation','thúc đẩy đồn đoán','His silence fueled speculation.','verb+noun',3],['cover a story','đưa tin một vụ việc','Journalists covered the story.','verb+noun',2],['go viral','lan truyền nhanh chóng','The video went viral overnight.','verb+adj',2]],
  9:[['carbon footprint','dấu chân carbon','We must reduce our carbon footprint.','noun+noun',2],['tackle climate change','giải quyết biến đổi khí hậu','Governments must tackle climate change.','verb+noun',2],['renewable energy','năng lượng tái tạo','Investment in renewable energy is growing.','adj+noun',2],['raise awareness','nâng cao nhận thức','The campaign raises awareness of pollution.','verb+noun',2],['sustainable development','phát triển bền vững','Sustainable development is essential.','adj+noun',2],['endangered species','loài có nguy cơ tuyệt chủng','Many endangered species need protection.','adj+noun',2],['environmental impact','tác động môi trường','Assess the environmental impact first.','adj+noun',2],['social inequality','bất bình đẳng xã hội','Social inequality remains a problem.','adj+noun',3],['alleviate poverty','xóa đói giảm nghèo','Efforts to alleviate poverty continue.','verb+noun',3],['bridge the gap','thu hẹp khoảng cách','Education can bridge the gap.','verb+noun',3],['ecological balance','cân bằng sinh thái','Human activity disrupts ecological balance.','adj+noun',3],['greenhouse gases','khí nhà kính','We must reduce greenhouse gas emissions.','adj+noun',2],['deforestation rate','tỷ lệ phá rừng','The deforestation rate is alarming.','noun+noun',3],['waste disposal','xử lý chất thải','Proper waste disposal is crucial.','noun+noun',2],['urban sprawl','sự mở rộng đô thị','Urban sprawl causes many problems.','adj+noun',3],['pose a threat','đặt ra mối đe dọa','Pollution poses a threat to health.','verb+noun',2],['exhaust resources','cạn kiệt tài nguyên','We are exhausting natural resources.','verb+noun',3],['biodiversity loss','mất đa dạng sinh học','Biodiversity loss is accelerating.','noun+noun',3],['fossil fuels','nhiên liệu hóa thạch','We must move away from fossil fuels.','adj+noun',2],['global warming','nóng lên toàn cầu','Global warming affects all countries.','adj+noun',2]],
  10:[['exert influence','gây ảnh hưởng','Governments exert influence over media.','verb+noun',3],['render assistance','hỗ trợ, giúp đỡ','They rendered assistance to victims.','verb+noun',4],['forge ahead','tiến lên phía trước','The company forged ahead with plans.','verb+adv',3],['exercise caution','thận trọng','You should exercise caution in this area.','verb+noun',3],['strike a balance','tìm sự cân bằng','We need to strike a balance.','verb+noun',3],['avert a crisis','ngăn chặn khủng hoảng','Quick action averted a crisis.','verb+noun',4],['gain insight','có được cái nhìn sâu sắc','Research gains insight into behavior.','verb+noun',3],['foster innovation','thúc đẩy đổi mới','Companies must foster innovation.','verb+noun',3],['bear in mind','ghi nhớ','Bear in mind that time is limited.','verb+prep',2],['draw a parallel','so sánh tương đồng','She drew a parallel between the two.','verb+noun',4],['raise an issue','nêu vấn đề','He raised an important issue.','verb+noun',2],['reach a consensus','đạt đồng thuận','The committee reached a consensus.','verb+noun',3],['pose a challenge','đặt ra thách thức','This poses a significant challenge.','verb+noun',3],['undergo treatment','trải qua điều trị','The patient underwent treatment.','verb+noun',3],['make a breakthrough','đạt bước đột phá','Scientists made a breakthrough.','verb+noun',3],['ease the burden','giảm bớt gánh nặng','Technology eases the burden.','verb+noun',3],['tackle a problem','giải quyết vấn đề','We must tackle this problem urgently.','verb+noun',2],['shed light on','làm sáng tỏ','The study shed light on the issue.','verb+prep',3],['take precedence','được ưu tiên','Safety takes precedence over speed.','verb+noun',3],['yield results','mang lại kết quả','The experiment yielded good results.','verb+noun',3]],
  11:[['draw a conclusion','rút ra kết luận','We can draw several conclusions.','verb+noun',2],['conduct a survey','tiến hành khảo sát','They conducted a nationwide survey.','verb+noun',2],['carry out research','thực hiện nghiên cứu','The team carried out extensive research.','verb+noun',2],['provide evidence','cung cấp bằng chứng','The data provides clear evidence.','verb+noun',2],['raise concerns','nêu lo ngại','Experts raised concerns about safety.','verb+noun',2],['address an issue','giải quyết vấn đề','The report addresses key issues.','verb+noun',3],['lend support to','ủng hộ','The findings lend support to the theory.','verb+prep',3],['come to fruition','đơm hoa kết trái','Years of work came to fruition.','verb+prep',4],['stand to reason','hợp lý','It stands to reason that this would work.','verb+prep',3],['take into consideration','cân nhắc','We must take all factors into consideration.','verb+prep',2],['in the light of','dưới ánh sáng của','In the light of new evidence...','prep+noun',3],['in conjunction with','kết hợp với','Used in conjunction with other methods.','prep+noun',3],['with regard to','liên quan đến','With regard to your question...','prep+noun',3],['on the grounds that','với lý do rằng','He was rejected on the grounds that...','prep+noun',3],['to a certain extent','ở một mức độ nhất định','To a certain extent, this is true.','prep+noun',2],['by and large','nói chung','By and large, results were positive.','adv',3],['for the time being','tạm thời','For the time being, we will wait.','prep+noun',2],['in the long run','về lâu dài','It will be beneficial in the long run.','prep+noun',2],['as a matter of fact','thực ra','As a matter of fact, he was right.','prep+noun',2],['without a shadow of doubt','không còn nghi ngờ gì','He is guilty without a shadow of doubt.','prep+noun',4]],
  12:[['get itchy feet','muốn đi du lịch','After a year, she got itchy feet.','verb+noun',4],['off the beaten track','nơi ít người đến','We found a cafe off the beaten track.','prep+noun',3],['foot the bill','thanh toán hóa đơn','Who is going to foot the bill?','verb+noun',3],['call for a celebration','xứng đáng ăn mừng','This calls for a celebration!','verb+prep',3],['play host to','làm chủ nhà','The city played host to the Olympics.','verb+prep',3],['broach the subject','khơi mào đề tài','She finally broached the subject.','verb+noun',4],['opening gambit','nước đi mở đầu','His opening gambit failed.','adj+noun',4],['juicy gossip','tin đồn thú vị','She loves sharing juicy gossip.','adj+noun',3],['propose a toast','nâng ly chúc mừng','Let me propose a toast to the couple.','verb+noun',3],['set the trend','tạo xu hướng','Paris always sets the trend.','verb+noun',3],['break new ground','mở ra hướng mới','The research broke new ground.','verb+noun',3],['turn a blind eye','làm ngơ','The police turned a blind eye.','verb+noun',3],['jump to conclusions','vội kết luận','Dont jump to conclusions.','verb+prep',2],['have second thoughts','phân vân lại','She had second thoughts about going.','verb+noun',2],['give the green light','cho phép','The council gave the green light.','verb+noun',3],['take something for granted','coi là hiển nhiên','Dont take your health for granted.','verb+prep',2],['cut corners','cắt giảm chi phí/chất lượng','They cut corners to save money.','verb+noun',3],['bite the bullet','chấp nhận điều khó khăn','She decided to bite the bullet.','verb+noun',3],['hit the nail on the head','nói trúng vấn đề','You hit the nail on the head.','verb+prep',3],['keep a low profile','giữ kín, không gây chú ý','He kept a low profile after the scandal.','verb+noun',3]],
  13:[['irreversible damage','thiệt hại không thể khắc phục','Pollution causes irreversible damage.','adj+noun',4],['launch a scathing attack','chỉ trích gay gắt','He launched a scathing attack on policy.','verb+noun',4],['extol virtues','ca ngợi phẩm chất','The teacher extolled the virtues of hard work.','verb+noun',4],['scupper a plan','phá hỏng kế hoạch','Bad weather scuppered our plans.','verb+noun',4],['carve a niche','tạo vị thế riêng','She carved a niche for herself.','verb+noun',4],['weather the storm','vượt qua khó khăn','The company weathered the storm.','verb+noun',3],['pave the way','mở đường','This discovery paved the way for progress.','verb+noun',3],['fall short of','không đạt được','Results fell short of expectations.','verb+prep',3],['come under scrutiny','bị giám sát','The decision came under scrutiny.','verb+prep',4],['bear the brunt','chịu gánh nặng lớn nhất','Workers bore the brunt of the cuts.','verb+noun',4],['stem the tide','ngăn chặn làn sóng','Efforts to stem the tide of crime.','verb+noun',4],['sound the alarm','gióng hồi chuông cảnh báo','Scientists sounded the alarm.','verb+noun',3],['turn the tide','đảo ngược tình thế','The new strategy turned the tide.','verb+noun',3],['run the risk','mạo hiểm','You run the risk of losing everything.','verb+noun',3],['stand ones ground','giữ vững lập trường','She stood her ground despite pressure.','verb+noun',3],['give rise to','gây ra, dẫn đến','This gave rise to many problems.','verb+prep',3],['go to great lengths','cố gắng hết sức','She went to great lengths to help.','verb+prep',3],['leave much to be desired','còn nhiều thiếu sót','Their service leaves much to be desired.','verb+prep',4],['take its toll','gây tổn thất','Stress takes its toll on health.','verb+noun',3],['lend itself to','phù hợp với','The topic lends itself to discussion.','verb+prep',4]],
  14:[['unprecedented scale','quy mô chưa từng có','Destruction on an unprecedented scale.','adj+noun',4],['contentious issue','vấn đề gây tranh cãi','Immigration is a contentious issue.','adj+noun',4],['stringent regulations','quy định nghiêm ngặt','The government imposed stringent regulations.','adj+noun',4],['stark contrast','tương phản rõ rệt','In stark contrast to previous results.','adj+noun',3],['sweeping changes','thay đổi toàn diện','The reforms brought sweeping changes.','adj+noun',3],['dwindling resources','tài nguyên cạn kiệt','Dwindling resources pose a challenge.','adj+noun',4],['pivotal role','vai trò then chốt','Education plays a pivotal role.','adj+noun',3],['resounding success','thành công vang dội','The event was a resounding success.','adj+noun',3],['formidable challenge','thách thức ghê gớm','This is a formidable challenge.','adj+noun',4],['vested interest','lợi ích cá nhân','He has a vested interest in the outcome.','adj+noun',4],['detrimental effect','tác động có hại','Smoking has a detrimental effect.','adj+noun',3],['inherent risk','rủi ro vốn có','There is an inherent risk in investing.','adj+noun',4],['paradigm shift','sự thay đổi mô hình','A paradigm shift in thinking occurred.','noun+noun',4],['overarching goal','mục tiêu bao trùm','The overarching goal is sustainability.','adj+noun',4],['ulterior motive','động cơ thầm kín','I suspect he has an ulterior motive.','adj+noun',4],['unequivocal support','ủng hộ rõ ràng','She gave her unequivocal support.','adj+noun',4],['mitigating circumstances','tình tiết giảm nhẹ','There were mitigating circumstances.','adj+noun',5],['pervasive influence','ảnh hưởng lan rộng','Social media has a pervasive influence.','adj+noun',4],['tangible results','kết quả hữu hình','The project produced tangible results.','adj+noun',3],['viable alternative','phương án khả thi','We need a viable alternative.','adj+noun',3]],
};

function autoSeed() {
  // Admin
  if (!queryOne("SELECT id FROM users WHERE username='admin'")) {
    runSql("INSERT INTO users (username,password,displayName,role) VALUES ('admin',?,'Admin','admin')", [bcrypt.hashSync(ADMIN_PASSWORD, 10)]);
    console.log('  ✅ Admin account created');
  }
  // Demo
  if (!queryOne("SELECT id FROM users WHERE username='demo'")) {
    runSql("INSERT INTO users (username,password,displayName,role) VALUES ('demo',?,'Học sinh Demo','student')", [bcrypt.hashSync('student123', 10)]);
    console.log('  ✅ Demo student created');
  }
  // Lessons
  if (queryOne('SELECT COUNT(*) as c FROM lessons').c === 0) {
    for (const l of lessons) runSql('INSERT INTO lessons (title,titleVi,description,descriptionVi,level,orderIndex,sourceReference,isGloballyLocked) VALUES (?,?,?,?,?,?,?,?)', [l.title, l.titleVi, l.desc, l.descVi, l.level, l.order, l.src, l.locked]);
    console.log(`  ✅ ${lessons.length} lessons`);
  }
  // Collocations
  if (queryOne('SELECT COUNT(*) as c FROM collocations').c === 0) {
    let t = 0;
    for (const [lid, items] of Object.entries(cols)) {
      for (const [col, vi, ex, type, diff] of items) { runSql('INSERT INTO collocations (lessonId,collocation,meaningVi,example,type,difficulty) VALUES (?,?,?,?,?,?)', [parseInt(lid), col, vi, ex, type, diff]); t++; }
    }
    console.log(`  ✅ ${t} collocations`);
  }
  // Auto-unlock
  const demo = queryOne("SELECT id FROM users WHERE username='demo'");
  if (demo) {
    const unlocked = queryAll('SELECT id FROM lessons WHERE isGloballyLocked=0');
    for (const l of unlocked) runSql("INSERT OR IGNORE INTO lesson_access (userId,lessonId,isUnlocked,unlockedAt) VALUES (?,?,1,datetime('now'))", [demo.id, l.id]);
  }
}

module.exports = { autoSeed };
